1-module
js-tasks-ru/jsbasic-20201008_pushkareva-nataly pull request #2
Opened 2020-10-20 12:19 UTC by tomby5475

2020-10-20 12:26 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-20 20:43 UTC, tomby5475 commented
Код проходит все тесты в консоли и лишних выводов нет, только те, что в условии.

> On 20. Oct 2020, at 14:26, javascript-ru <notifications@github.com> wrote:
> 
> 
> Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
> выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
> (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/js-tasks-ru/jsbasic-20201008_pushkareva-nataly/pull/2#issuecomment-712812522>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ALV4J76T64LZUDC2TPIE4JDSLV6WVANCNFSM4SYIOQBA>.
>

2020-10-21 09:33 UTC, stas-dolgachov requested changes

2020-10-21 09:33 UTC, stas-dolgachov commented on 1-module/2-task/index.js
> +sayHello();
Удалите, пожалуйста, вот этот вызов. Из-за него тест не проходит.

2020-10-21 09:48 UTC, tomby5475 commented
Done

> On 21. Oct 2020, at 11:33, Stanislav <notifications@github.com> wrote:
> 
> 
> @stas-dolgachov requested changes on this pull request.
> 
> In 1-module/2-task/index.js <https://github.com/js-tasks-ru/jsbasic-20201008_pushkareva-nataly/pull/2#discussion_r509132618>:
> 
> > @@ -22,3 +20,5 @@ function sayHello() {
>      print('Некорректное имя');
>    }
>  }
> +
> +sayHello();
> Удалите, пожалуйста, вот этот вызов. Из-за него тест не проходит.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/js-tasks-ru/jsbasic-20201008_pushkareva-nataly/pull/2#pullrequestreview-513485922>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ALV4J77TOEWEPEXJNZEGHFTSL2TG7ANCNFSM4SYIOQBA>.
>

2020-10-21 09:59 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Допишите функцию валидации имени пользователя
+ если меньше 4 символов то false
+ если содержит пробелы, то false
+ если имя корректное, то true
```
```diff
Сделать первый символ заглавным
+ должна делать первый символ заглавным
+ должна работать для строки из одной буквы
+ должна работать для пустой строки
```
```diff
Усечение строки
+ должна не трогать короткую строку 
+ должна усекать строку 
```
```diff
Проверка на спам
+ должна возвращать false для 'innocent rabbit'
+ должна возвращать true для 'free xxxxx'
+ должна возвращать true для '1XbeT now'
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-10-21 17:54 UTC, stas-dolgachov approved these changes

2020-10-21 17:55 UTC, merged